export enum AppActions {
  REQUEST_FETCH_PATIENT = 'REQUEST_FETCH_PATIENT',
  REQUEST_CREATE_EPISODE = 'REQUEST_CREATE_EPISODE',
  REQUEST_UPDATE_EPISODE = 'REQUEST_UPDATE_EPISODE',
  REQUEST_FETCH_EPISODES = 'REQUEST_FETCH_EPISODES',
  REQUEST_FETCH_REPORTS = 'REQUEST_FETCH_REPORTS',
  REQUEST_FETCH_REPORTS_EPISODES_RANGE = 'REQUEST_FETCH_REPORTS_EPISODES_RANGE',
}
